title: habd.as
description: Tech tutorials and other tidbits
disqus_shortname: habdas
reading_time: true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://habd.as

# Owner/author information
owner:
  name: Josh Habdas
  avatar: avatar.jpg
  bio: "I'm a front-end developer constantly toiling to create fast, usable web apps."
  email: jhabdas@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: jhabdas
  facebook:
  github: jhabdas
  # stackexchange: 366663
  linkedin: jhabdas
  instagram: jhabdas
  # flickr: 44745799@N08
  # tumblr: jhabdas
  google_plus: +JoshHabdas

excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# Background image to be tiled on all pages
background: witewall_3.png

# Analytics and webmaster tools stuff goes here
google_analytics: # UA-6473963-1 disabled in favor of Analytics tag for Tag Manager
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Chicago
future: true
gems:
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# http://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Amount of post to show on home page
paginate: 5

# Conversion
markdown: KramdownPygments

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
