# Site Settings (Development Overrides)

url: http://localhost:4000

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

analytics:
  provider: false

comments:
  provider: false
